name: Deploy demo ledger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-ledger:
    name: Deploy ledger
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Create identity file
      env:
        KEY: ${{ secrets.DEMO_LEDGER_KEY }}
      run: |
        echo "$KEY" | base64 --decode >ledger.key
        chmod 400 ledger.key

    - name: Deploy
      run: |
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ledger.key ubuntu@${{ secrets.DEMO_LEDGER_IP }} git -C /home/ubuntu/von-network fetch origin
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ledger.key ubuntu@${{ secrets.DEMO_LEDGER_IP }} git -C /home/ubuntu/von-network checkout "${GITHUB_SHA}"
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ledger.key ubuntu@${{ secrets.DEMO_LEDGER_IP }} /home/ubuntu/von-network/.github/scripts/blog3-deploy-ledger.sh
        ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ledger.key ubuntu@${{ secrets.DEMO_LEDGER_IP }} /home/ubuntu/von-network/.github/scripts/blog3-register-dids.sh /home/ubuntu/seeds.txt
